language: node_js
node_js:
  - "0.10"
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#YOUR-IRC-CHANNEL"
    template:
      - "%{repository}#%{build_number} (on %{branch} by %{author}): %{message} %{build_url}"
